Add missing `import pickle` to `deep_arch.py`
Otherwise get:

```
$ python3 deep_arch.py
...
Traceback (most recent call last):
  File "/home/benjamin/UMAP23_KARSCombiningGNNsEncSentenceEnc/deep_arch.py", line 229, in <module>
    graph_emb = pickle.load(open(source_graph_path, 'rb'))
NameError: name 'pickle' is not defined
```