Use `model_entity_dropout_selfatt_crossatt` instead of not existing `run_layers_entity_dropout_selfatt_crossatt`
Otherwise get:

```
Traceback (most recent call last):
  File "/home/debian/UMAP23_KARSCombiningGNNsEncSentenceEnc/deep_arch.py", line 248, in <module>
    recsys_model = run_layers_entity_dropout_selfatt_crossatt(X,y,dim_embeddings,epochs=30,batch_size=512, value=0.7)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'run_layers_entity_dropout_selfatt_crossatt' is not defined. Did you mean: 'model_entity_dropout_selfatt_crossatt'?
```