Add missing `import os` to `deep_arch.py`
Otherwise get:

```
$ python3 deep_arch.py
...
Traceback (most recent call last):
  File "/home/benjamin/UMAP23_KARSCombiningGNNsEncSentenceEnc/deep_arch.py", line 235, in <module>
    if os.path.exists(model_path):
NameError: name 'os' is not defined
```