Use `sentence-transformers/all-MiniLM-L12-v1` instead of `sentence-transformers/sota_minilm-l12-v1`, as it is no more available
Otherwise face:

```
DEBUG:urllib3.connectionpool:https://huggingface.co:443 "GET /api/models/sentence-transformers/sota_minilm-l12-v1 HTTP/1.1" 401 41
Traceback (most recent call last):
  File "/home/benjamin/.local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 270, in hf_raise_for_status
    response.raise_for_status()
  File "/home/benjamin/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/sentence-transformers/sota_minilm-l12-v1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/benjamin/Desktop/bens_folder/school/aria/project/UMAP23_KARSCombiningGNNsEncSentenceEnc/learn_sent_embeddings.py", line 16, in <module>
    model = SentenceTransformer('sota_minilm-l12-v1')
  File "/home/benjamin/.local/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 91, in __init__
    snapshot_download(model_name_or_path,
  File "/home/benjamin/.local/lib/python3.10/site-packages/sentence_transformers/util.py", line 443, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
  File "/home/benjamin/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/benjamin/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1922, in model_info
    hf_raise_for_status(r)
  File "/home/benjamin/.local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 320, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-655c2fe3-63c715d0239caac83de73041;a66d76a3-49f2-4ee4-b16e-c7ce83eb842d)

Repository Not Found for url: https://huggingface.co/api/models/sentence-transformers/sota_minilm-l12-v1.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
```

As https://huggingface.co/sentence-transformers/sota_minilm-l12-v1
returns an error while
https://huggingface.co/sentence-transformers/all-MiniLM-L12-v1 does not.